chs.url=${CHS_URL}
developer.url=${DEVELOPER_URL}
account.url=${ACCOUNT_LOCAL_URL}
monitorGui.url=${CHS_MONITOR_GUI_URL}
cdn.url=//${CDN_HOST}
enquiries=${ENQUIRY_EMAIL}
piwik.url=${PIWIK_URL}
piwik.siteId=${PIWIK_SITE_ID}
feedback.url=${FEEDBACK_URL}
contactUs.url=${CONTACT_US_URL}
policies.url=${POLICIES_URL}

# Presenter journey
acsp.sign-in.url=${ACSP_SIGN_IN_URL:"placeholder"}
identity.verification.url=${IDENTITY_VERIFICATION_URL:"placeholder"}
chs.jwt.secret=${CHS_JWT_SECRET}

management.endpoints.access.default=read_only
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=/transaction/healthcheck
management.endpoint.health.show-details=never
management.endpoints.web.exposure.include=health

management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics

